import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import TanstackProvider from "@/components/providers/TanstackProvider";
import ContextProvider from "@/components/providers/ContextProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body >
    <TanstackProvider>
    <ContextProvider>
    <div className="min-h-screen flex flex-col">
        <Nav/>
         <main  className="flex-1">
           {children} 
         </main>
       <Footer/>
       </div>
       </ContextProvider>
    </TanstackProvider>
        </body>
    </html>
  );
}
